// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumedadChange();
void onTemperaturaChange();
void onRgbColorChange();
void onHumedadValorChange();
void onLuzChange();
void onActualizacionPantallaChange();
void onRele1Change();
void onRele2Change();

float humedad;
float temperatura;
CloudColoredLight rgbColor;
int humedadValor;
int luz;
bool actualizacionPantalla;
bool rele_1;
bool rele_2;

void initProperties(){

  ArduinoCloud.addProperty(humedad, READWRITE, 1 * SECONDS, onHumedadChange);
  ArduinoCloud.addProperty(temperatura, READWRITE, 1 * SECONDS, onTemperaturaChange);
  ArduinoCloud.addProperty(rgbColor, READWRITE, ON_CHANGE, onRgbColorChange);
  ArduinoCloud.addProperty(humedadValor, READWRITE, 1 * SECONDS, onHumedadValorChange);
  ArduinoCloud.addProperty(luz, READWRITE, 1 * SECONDS, onLuzChange);
  ArduinoCloud.addProperty(actualizacionPantalla, READWRITE, ON_CHANGE, onActualizacionPantallaChange);
  ArduinoCloud.addProperty(rele_1, READWRITE, ON_CHANGE, onRele1Change);
  ArduinoCloud.addProperty(rele_2, READWRITE, ON_CHANGE, onRele2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
